### PR TITLE
chore(package): bump dependencies

### PR DESCRIPTION
**Pull request by danielsogl**

### CODE REVIEW

**Comment by Pupix** [comment]
Hello!

I am trying to move away from the `^` range and keep the versions exact and stable, just like [shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) to avoid "same version, different dependencies" type problems. If you can fix that I will merge this.

Thanks!

**Comment by Pupix** [comment]
`lol-riot-api-module` should have its range removed too.

**Comment by danielsogl** [comment]
Done

**Comment by Pupix** [comment]
Thanks!

**Comment by danielsogl** [comment]
You closed it ^^

**Pull request closed without merging**
